extends Node

var CharacterDictSingles = {
	"Mario": 70,
	"Donkey Kong": 70,
	"Link": 55,
	"Samus": 65,
	"Dark Samus": 65,
	"Yoshi": 75,
	"Kirby": 70,
	"Fox": 55,
	"Pikachu": 60,
	"Luigi": 60,
	"Ness": 65,
	"Captain Falcon": 65,
	"Jigglypuff": 40,
	"Peach": 60,
	"Daisy": 60,
	"Bowser": 75,
	"Ice Climbers": 70,
	"Sheik": 30,
	"Zelda": 40,
	"Dr. Mario": 75,
	"Pichu": 60,
	"Falco": 65,
	"Marth": 55,
	"Lucina": 55,
	"Young Link": 50,
	"Ganondorf": 65,
	"Mewtwo": 65,
	"Roy": 55,
	"Chrom": 70,
	"Mr. Game & Watch": 65,
	"Meta Knight": 60,
	"Pit": 65,
	"Dark Pit": 80,
	"Zero Suit Samus": 35,
	"Wario": 65,
	"Snake": 75,
	"Ike": 75,
	"Pokemon Trainer": 60,
	"Diddy Kong": 45,
	"Lucas": 80,
	"Sonic": 80,
	"King Dedede": 70,
	"Olimar": 65,
	"Lucario": 65,
	"R.O.B.": 60,
	"Toon Link": 40,
	"Wolf": 65,
	"Villager": 65,
	"Mega Man": 80,
	"Wii Fit Trainer": 65,
	"Rosalina & Luma": 55,
	"Little Mac": 65,
	"Greninja": 50,
	"Palutena": 65,
	"PAC-Man": 70,
	"Robin": 75,
	"Shulk": 65,
	"Bowser Jr.": 60,
	"Duck Hunt": 45,
	"Ryu": 70,
	"Ken": 45,
	"Cloud": 75,
	"Corrin": 60,
	"Bayonetta": 40,
	"Inkling": 65,
	"Ridley": 65,
	"Simon": 70,
	"Richter": 70,
	"King K. Rool": 75,
	"Isabelle": 65,
	"Incineroar": 60,
	"Piranha Plant": 60,
	"Joker": 65,
	"Hero": 75,
	"Banjo & Kazooie": 65,
	"Terry": 70,
	"Byleth": 80,
	"Min Min": 65,
	"Steve": 75,
	"Sephiroth": 60,
	"Pyra/Mythra": 70,
	"Kazuya": 55,
	"Sora": 70,
	"Mii Brawler": 60,
	"Mii Swordfighter": 75,
	"Mii Gunner": 65,
}

var CharacterDictFinalSmash = {
	"Mario": 65,
	"Donkey Kong": 70,
	"Link": 65,
	"Samus": 65,
	"Dark Samus": 65,
	"Yoshi": 85,
	"Kirby": 75,
	"Fox": 55,
	"Pikachu": 60,
	"Luigi": 70,
	"Ness": 65,
	"Captain Falcon": 65,
	"Jigglypuff": 35,
	"Peach": 45,
	"Daisy": 45,
	"Bowser": 75,
	"Ice Climbers": 60,
	"Sheik": 40,
	"Zelda": 70,
	"Dr. Mario": 65,
	"Pichu": 60,
	"Falco": 65,
	"Marth": 60,
	"Lucina": 60,
	"Young Link": 70,
	"Ganondorf": 65,
	"Mewtwo": 70,
	"Roy": 60,
	"Chrom": 80,
	"Mr. Game & Watch": 55,
	"Meta Knight": 55,
	"Pit": 75,
	"Dark Pit": 85,
	"Zero Suit Samus": 70,
	"Wario": 75,
	"Snake": 85,
	"Ike": 75,
	"Pokemon Trainer": 65,
	"Diddy Kong": 70,
	"Lucas": 65,
	"Sonic": 85,
	"King Dedede": 70,
	"Olimar": 55,
	"Lucario": 80,
	"R.O.B.": 75,
	"Toon Link": 70,
	"Wolf": 65,
	"Villager": 70,
	"Mega Man": 80,
	"Wii Fit Trainer": 55,
	"Rosalina & Luma": 65,
	"Little Mac": 65,
	"Greninja": 50,
	"Palutena": 70,
	"PAC-Man": 70,
	"Robin": 75,
	"Shulk": 60,
	"Bowser Jr.": 75,
	"Duck Hunt": 45,
	"Ryu": 75,
	"Ken": 45,
	"Cloud": 75,
	"Corrin": 55,
	"Bayonetta": 35,
	"Inkling": 55,
	"Ridley": 75,
	"Simon": 70,
	"Richter": 70,
	"King K. Rool": 75,
	"Isabelle": 70,
	"Incineroar": 70,
	"Piranha Plant": 65,
	"Joker": 60,
	"Hero": 75,
	"Banjo & Kazooie": 75,
	"Terry": 70,
	"Byleth": 80,
	"Min Min": 65,
	"Steve": 75,
	"Sephiroth": 55,
	"Pyra/Mythra": 70,
	"Kazuya": 50,
	"Sora": 60,
	"Mii Brawler": 55,
	"Mii Swordfighter": 60,
	"Mii Gunner": 65,
}

var CharacterDictStamina = {
	"Mario": 70,
	"Donkey Kong": 50,
	"Link": 60,
	"Samus": 50,
	"Dark Samus": 50,
	"Yoshi": 60,
	"Kirby": 70,
	"Fox": 70,
	"Pikachu": 85,
	"Luigi": 40,
	"Ness": 75,
	"Captain Falcon": 70,
	"Jigglypuff": 70,
	"Peach": 70,
	"Daisy": 70,
	"Bowser": 65,
	"Ice Climbers": 75,
	"Sheik": 40,
	"Zelda": 65,
	"Dr. Mario": 65,
	"Pichu": 100,
	"Falco": 50,
	"Marth": 35,
	"Lucina": 35,
	"Young Link": 90,
	"Ganondorf": 60,
	"Mewtwo": 50,
	"Roy": 70,
	"Chrom": 50,
	"Mr. Game & Watch": 75,
	"Meta Knight": 55,
	"Pit": 45,
	"Dark Pit": 70,
	"Zero Suit Samus": 40,
	"Wario": 50,
	"Snake": 65,
	"Ike": 60,
	"Pokemon Trainer": 65,
	"Diddy Kong": 60,
	"Lucas": 60,
	"Sonic": 70,
	"King Dedede": 65,
	"Olimar": 95,
	"Lucario": 60,
	"R.O.B.": 40,
	"Toon Link": 90,
	"Wolf": 80,
	"Villager": 50,
	"Mega Man": 60,
	"Wii Fit Trainer": 45,
	"Rosalina & Luma": 55,
	"Little Mac": 60,
	"Greninja": 60,
	"Palutena": 50,
	"PAC-Man": 50,
	"Robin": 60,
	"Shulk": 55,
	"Bowser Jr.": 60,
	"Duck Hunt": 75,
	"Ryu": 85,
	"Ken": 60,
	"Cloud": 80,
	"Corrin": 70,
	"Bayonetta": 40,
	"Inkling": 80,
	"Ridley": 60,
	"Simon": 70,
	"Richter": 70,
	"King K. Rool": 45,
	"Isabelle": 55,
	"Incineroar": 70,
	"Piranha Plant": 50,
	"Joker": 65,
	"Hero": 55,
	"Banjo & Kazooie": 75,
	"Terry": 80,
	"Byleth": 55,
	"Min Min": 70,
	"Steve": 65,
	"Sephiroth": 40,
	"Pyra/Mythra": 80,
	"Kazuya": 80,
	"Sora": 70,
	"Mii Brawler": 75,
	"Mii Swordfighter": 65,
	"Mii Gunner": 70,
}

var CharacterDictDoubles = {
	"Mario": 55,
	"Donkey Kong": 65,
	"Link": 60,
	"Samus": 75,
	"Dark Samus": 75,
	"Yoshi": 60,
	"Kirby": 65,
	"Fox": 55,
	"Pikachu": 55,
	"Luigi": 55,
	"Ness": 75,
	"Captain Falcon": 55,
	"Jigglypuff": 75,
	"Peach": 65,
	"Daisy": 65,
	"Bowser": 90,
	"Ice Climbers": 50,
	"Sheik": 40,
	"Zelda": 65,
	"Dr. Mario": 65,
	"Pichu": 45,
	"Falco": 65,
	"Marth": 80,
	"Lucina": 80,
	"Young Link": 45,
	"Ganondorf": 55,
	"Mewtwo": 65,
	"Roy": 55,
	"Chrom": 60,
	"Mr. Game & Watch": 60,
	"Meta Knight": 55,
	"Pit": 55,
	"Dark Pit": 70,
	"Zero Suit Samus": 50,
	"Wario": 55,
	"Snake": 55,
	"Ike": 60,
	"Pokemon Trainer": 55,
	"Diddy Kong": 65,
	"Lucas": 75,
	"Sonic": 70,
	"King Dedede": 80,
	"Olimar": 55,
	"Lucario": 55,
	"R.O.B.": 55,
	"Toon Link": 40,
	"Wolf": 50,
	"Villager": 55,
	"Mega Man": 70,
	"Wii Fit Trainer": 65,
	"Rosalina & Luma": 55,
	"Little Mac": 45,
	"Greninja": 60,
	"Palutena": 90,
	"PAC-Man": 90,
	"Robin": 65,
	"Shulk": 55,
	"Bowser Jr.": 45,
	"Duck Hunt": 40,
	"Ryu": 55,
	"Ken": 50,
	"Cloud": 70,
	"Corrin": 55,
	"Bayonetta": 40,
	"Inkling": 65,
	"Ridley": 55,
	"Simon": 50,
	"Richter": 50,
	"King K. Rool": 60,
	"Isabelle": 65,
	"Incineroar": 45,
	"Piranha Plant": 65,
	"Joker": 55,
	"Hero": 65,
	"Banjo & Kazooie": 55,
	"Terry": 55,
	"Byleth": 85,
	"Min Min": 55,
	"Steve": 60,
	"Sephiroth": 80,
	"Pyra/Mythra": 55,
	"Kazuya": 45,
	"Sora": 70,
	"Mii Brawler": 55,
	"Mii Swordfighter": 65,
	"Mii Gunner": 75,
}

func _ready():
	pass

# Called every frame. 'delta' is the elapsed time since the previous frame.
func _process(delta):
	pass

func set_rating(Name, Mode, Amount):
	if Mode == "Singles":
		CharacterDictSingles[Name] = Amount
	if Mode == "Final Smash":
		CharacterDictFinalSmash[Name] = Amount
	if Mode == "Stamina":
		CharacterDictStamina[Name] = Amount
	if Mode == "Doubles":
		CharacterDictDoubles[Name] = Amount
	
func get_rating(Name, Mode):
	if Mode == "Singles":
		print("Character: " + Name + ", Mode: " + Mode + ", Rating: " + str(CharacterDictSingles[Name]))
		return CharacterDictSingles[Name]
	if Mode == "Final Smash":
		print("Character: " + Name + ", Mode: " + Mode + ", Rating: " + str(CharacterDictFinalSmash[Name]))
		return CharacterDictFinalSmash[Name]
	if Mode == "Stamina":
		print("Character: " + Name + ", Mode: " + Mode + ", Rating: " + str(CharacterDictStamina[Name]))
		return CharacterDictStamina[Name]
	if Mode == "Doubles":
		print("Character: " + Name + ", Mode: " + Mode + ", Rating: " + str(CharacterDictDoubles[Name]))
		return CharacterDictDoubles[Name]
