extends Node

var leaguescheduleweek

# Called when the node enters the scene tree for the first time.
func _ready() -> void:
	leaguescheduleweek = Global.SeasonWeek
	schedule_view()

# Called every frame. 'delta' is the elapsed time since the previous frame.
func _process(delta: float) -> void:
	pass

func schedule_view():
	
	if leaguescheduleweek <= 12:
		$First10/ColorRect/Match1.text = "Week " + str(leaguescheduleweek) + ": " + Schedule.get_schedule((leaguescheduleweek * 20) - 19, 0) + " vs. " + Schedule.get_schedule((leaguescheduleweek * 20) - 19, 1)
		$First10/ColorRect2/Match2.text = "Week " + str(leaguescheduleweek) + ": " + Schedule.get_schedule((leaguescheduleweek * 20) - 18, 0) + " vs. " + Schedule.get_schedule((leaguescheduleweek * 20) - 18, 1)
		$First10/ColorRect3/Match3.text = "Week " + str(leaguescheduleweek) + ": " + Schedule.get_schedule((leaguescheduleweek * 20) - 17, 0) + " vs. " + Schedule.get_schedule((leaguescheduleweek * 20) - 17, 1)
		$First10/ColorRect4/Match4.text = "Week " + str(leaguescheduleweek) + ": " + Schedule.get_schedule((leaguescheduleweek * 20) - 16, 0) + " vs. " + Schedule.get_schedule((leaguescheduleweek * 20) - 16, 1)
		$First10/ColorRect5/Match5.text = "Week " + str(leaguescheduleweek) + ": " + Schedule.get_schedule((leaguescheduleweek * 20) - 15, 0) + " vs. " + Schedule.get_schedule((leaguescheduleweek * 20) - 15, 1)
		$First10/ColorRect6/Match6.text = "Week " + str(leaguescheduleweek) + ": " + Schedule.get_schedule((leaguescheduleweek * 20) - 14, 0) + " vs. " + Schedule.get_schedule((leaguescheduleweek * 20) - 14, 1)
		$First10/ColorRect7/Match7.text = "Week " + str(leaguescheduleweek) + ": " + Schedule.get_schedule((leaguescheduleweek * 20) - 13, 0) + " vs. " + Schedule.get_schedule((leaguescheduleweek * 20) - 13, 1)
		$First10/ColorRect8/Match8.text = "Week " + str(leaguescheduleweek) + ": " + Schedule.get_schedule((leaguescheduleweek * 20) - 12, 0) + " vs. " + Schedule.get_schedule((leaguescheduleweek * 20) - 12, 1)
		$First10/ColorRect9/Match9.text = "Week " + str(leaguescheduleweek) + ": " + Schedule.get_schedule((leaguescheduleweek * 20) - 11, 0) + " vs. " + Schedule.get_schedule((leaguescheduleweek * 20) - 11, 1)
		$First10/ColorRect10/Match10.text = "Week " + str(leaguescheduleweek) + ": " + Schedule.get_schedule((leaguescheduleweek * 20) - 10, 0) + " vs. " + Schedule.get_schedule((leaguescheduleweek * 20) - 10, 1)
		$Last10/ColorRect/Match1.text = "Week " + str(leaguescheduleweek) + ": " + Schedule.get_schedule((leaguescheduleweek * 20) - 9, 0) + " vs. " + Schedule.get_schedule((leaguescheduleweek * 20) - 9, 1)
		$Last10/ColorRect2/Match2.text = "Week " + str(leaguescheduleweek) + ": " + Schedule.get_schedule((leaguescheduleweek * 20) - 8, 0) + " vs. " + Schedule.get_schedule((leaguescheduleweek * 20) - 8, 1)
		$Last10/ColorRect3/Match3.text = "Week " + str(leaguescheduleweek) + ": " + Schedule.get_schedule((leaguescheduleweek * 20) - 7, 0) + " vs. " + Schedule.get_schedule((leaguescheduleweek * 20) - 7, 1)
		$Last10/ColorRect4/Match4.text = "Week " + str(leaguescheduleweek) + ": " + Schedule.get_schedule((leaguescheduleweek * 20) - 6, 0) + " vs. " + Schedule.get_schedule((leaguescheduleweek * 20) - 6, 1)
		$Last10/ColorRect5/Match5.text = "Week " + str(leaguescheduleweek) + ": " + Schedule.get_schedule((leaguescheduleweek * 20) - 5, 0) + " vs. " + Schedule.get_schedule((leaguescheduleweek * 20) - 5, 1)
		$Last10/ColorRect6/Match6.text = "Week " + str(leaguescheduleweek) + ": " + Schedule.get_schedule((leaguescheduleweek * 20) - 4, 0) + " vs. " + Schedule.get_schedule((leaguescheduleweek * 20) - 4, 1)
		$Last10/ColorRect7/Match7.text = "Week " + str(leaguescheduleweek) + ": " + Schedule.get_schedule((leaguescheduleweek * 20) - 3, 0) + " vs. " + Schedule.get_schedule((leaguescheduleweek * 20) - 3, 1)
		$Last10/ColorRect8/Match8.text = "Week " + str(leaguescheduleweek) + ": " + Schedule.get_schedule((leaguescheduleweek * 20) - 2, 0) + " vs. " + Schedule.get_schedule((leaguescheduleweek * 20) - 2, 1)
		$Last10/ColorRect9/Match9.text = "Week " + str(leaguescheduleweek) + ": " + Schedule.get_schedule((leaguescheduleweek * 20) - 1, 0) + " vs. " + Schedule.get_schedule((leaguescheduleweek * 20) - 1, 1)
		$Last10/ColorRect10/Match10.text = "Week " + str(leaguescheduleweek) + ": " + Schedule.get_schedule((leaguescheduleweek * 20) - 0, 0) + " vs. " + Schedule.get_schedule((leaguescheduleweek * 20) - 0, 1)
	else:
		$First10/ColorRect/Match1.text = "Alpha Conference Quarterfinals: 1 vs 8"
		$First10/ColorRect2/Match2.text = "Alpha Conference Quarterfinals: 2 vs 7"
		$First10/ColorRect3/Match3.text = "Alpha Conference Quarterfinals: 3 vs 6"
		$First10/ColorRect4/Match4.text = "Alpha Conference Quarterfinals: 4 vs 5"
		$First10/ColorRect5/Match5.text = "Omega Conference Quarterfinals: 1 vs 8"
		$First10/ColorRect6/Match6.text = "Omega Conference Quarterfinals: 2 vs 7"
		$First10/ColorRect7/Match7.text = "Omega Conference Quarterfinals: 3 vs 6"
		$First10/ColorRect8/Match8.text = "Omega Conference Quarterfinals: 4 vs 5"
		$First10/ColorRect9/Match9.text = "Alpha Conference Semifinals: 1/8 vs 4/5"
		$First10/ColorRect10/Match10.text = "Alpha Conference Semifinals: 2/7 vs 3/6"
		$Last10/ColorRect/Match1.text = "Omega Conference Semifinals: 1/8 vs 4/5"
		$Last10/ColorRect2/Match2.text = "Omega Conference Semifinals: 2/7 vs 3/6"
		$Last10/ColorRect3/Match3.text = "Alpha Conference Finals"
		$Last10/ColorRect4/Match4.text = "Omega Conference Finals"
		$Last10/ColorRect5/Match5.text = "Ultimate Draft League Championship"
		$Last10/ColorRect6/Match6.text = "N/A"
		$Last10/ColorRect7/Match7.text = "N/A"
		$Last10/ColorRect8/Match8.text = "N/A"
		$Last10/ColorRect9/Match9.text = "N/A"
		$Last10/ColorRect10/Match10.text = "N/A"
	

	if Global.SeasonWeek >= 2 and leaguescheduleweek == 1:
		$First10/ColorRect/Match1.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 20, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 20, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 20, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 20, 3))
		$First10/ColorRect2/Match2.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 19, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 19, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 19, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 19, 3))
		$First10/ColorRect3/Match3.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 18, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 18, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 18, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 18, 3))
		$First10/ColorRect4/Match4.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 17, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 17, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 17, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 17, 3))
		$First10/ColorRect5/Match5.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 16, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 16, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 16, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 16, 3))
		$First10/ColorRect6/Match6.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 15, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 15, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 15, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 15, 3))
		$First10/ColorRect7/Match7.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 14, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 14, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 14, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 14, 3))
		$First10/ColorRect8/Match8.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 13, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 13, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 13, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 13, 3))
		$First10/ColorRect9/Match9.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 12, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 12, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 12, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 12, 3))
		$First10/ColorRect10/Match10.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 11, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 11, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 11, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 11, 3))
		$Last10/ColorRect/Match1.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 10, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 10, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 10, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 10, 3))
		$Last10/ColorRect2/Match2.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 9, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 9, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 9, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 9, 3))
		$Last10/ColorRect3/Match3.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 8, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 8, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 8, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 8, 3))
		$Last10/ColorRect4/Match4.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 7, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 7, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 7, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 7, 3))
		$Last10/ColorRect5/Match5.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 6, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 6, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 6, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 6, 3))
		$Last10/ColorRect6/Match6.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 5, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 5, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 5, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 5, 3))
		$Last10/ColorRect7/Match7.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 4, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 4, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 4, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 4, 3))
		$Last10/ColorRect8/Match8.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 3, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 3, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 3, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 3, 3))
		$Last10/ColorRect9/Match9.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 2, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 2, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 2, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 2, 3))
		$Last10/ColorRect10/Match10.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 1, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 1, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 1, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 1, 3))
	
	if Global.SeasonWeek >= 3 and leaguescheduleweek == 2:
		$First10/ColorRect/Match1.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 20, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 20, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 20, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 20, 3))
		$First10/ColorRect2/Match2.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 19, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 19, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 19, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 19, 3))
		$First10/ColorRect3/Match3.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 18, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 18, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 18, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 18, 3))
		$First10/ColorRect4/Match4.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 17, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 17, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 17, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 17, 3))
		$First10/ColorRect5/Match5.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 16, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 16, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 16, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 16, 3))
		$First10/ColorRect6/Match6.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 15, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 15, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 15, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 15, 3))
		$First10/ColorRect7/Match7.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 14, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 14, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 14, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 14, 3))
		$First10/ColorRect8/Match8.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 13, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 13, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 13, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 13, 3))
		$First10/ColorRect9/Match9.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 12, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 12, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 12, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 12, 3))
		$First10/ColorRect10/Match10.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 11, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 11, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 11, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 11, 3))
		$Last10/ColorRect/Match1.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 10, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 10, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 10, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 10, 3))
		$Last10/ColorRect2/Match2.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 9, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 9, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 9, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 9, 3))
		$Last10/ColorRect3/Match3.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 8, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 8, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 8, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 8, 3))
		$Last10/ColorRect4/Match4.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 7, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 7, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 7, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 7, 3))
		$Last10/ColorRect5/Match5.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 6, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 6, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 6, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 6, 3))
		$Last10/ColorRect6/Match6.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 5, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 5, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 5, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 5, 3))
		$Last10/ColorRect7/Match7.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 4, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 4, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 4, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 4, 3))
		$Last10/ColorRect8/Match8.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 3, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 3, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 3, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 3, 3))
		$Last10/ColorRect9/Match9.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 2, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 2, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 2, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 2, 3))
		$Last10/ColorRect10/Match10.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 1, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 1, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 1, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 1, 3))

	if Global.SeasonWeek >= 4 and leaguescheduleweek == 3:
		$First10/ColorRect/Match1.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 20, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 20, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 20, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 20, 3))
		$First10/ColorRect2/Match2.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 19, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 19, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 19, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 19, 3))
		$First10/ColorRect3/Match3.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 18, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 18, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 18, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 18, 3))
		$First10/ColorRect4/Match4.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 17, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 17, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 17, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 17, 3))
		$First10/ColorRect5/Match5.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 16, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 16, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 16, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 16, 3))
		$First10/ColorRect6/Match6.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 15, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 15, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 15, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 15, 3))
		$First10/ColorRect7/Match7.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 14, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 14, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 14, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 14, 3))
		$First10/ColorRect8/Match8.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 13, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 13, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 13, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 13, 3))
		$First10/ColorRect9/Match9.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 12, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 12, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 12, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 12, 3))
		$First10/ColorRect10/Match10.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 11, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 11, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 11, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 11, 3))
		$Last10/ColorRect/Match1.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 10, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 10, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 10, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 10, 3))
		$Last10/ColorRect2/Match2.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 9, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 9, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 9, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 9, 3))
		$Last10/ColorRect3/Match3.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 8, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 8, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 8, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 8, 3))
		$Last10/ColorRect4/Match4.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 7, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 7, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 7, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 7, 3))
		$Last10/ColorRect5/Match5.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 6, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 6, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 6, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 6, 3))
		$Last10/ColorRect6/Match6.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 5, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 5, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 5, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 5, 3))
		$Last10/ColorRect7/Match7.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 4, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 4, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 4, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 4, 3))
		$Last10/ColorRect8/Match8.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 3, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 3, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 3, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 3, 3))
		$Last10/ColorRect9/Match9.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 2, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 2, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 2, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 2, 3))
		$Last10/ColorRect10/Match10.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 1, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 1, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 1, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 1, 3))

	if Global.SeasonWeek >= 5 and leaguescheduleweek == 4:
		$First10/ColorRect/Match1.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 20, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 20, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 20, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 20, 3))
		$First10/ColorRect2/Match2.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 19, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 19, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 19, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 19, 3))
		$First10/ColorRect3/Match3.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 18, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 18, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 18, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 18, 3))
		$First10/ColorRect4/Match4.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 17, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 17, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 17, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 17, 3))
		$First10/ColorRect5/Match5.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 16, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 16, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 16, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 16, 3))
		$First10/ColorRect6/Match6.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 15, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 15, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 15, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 15, 3))
		$First10/ColorRect7/Match7.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 14, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 14, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 14, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 14, 3))
		$First10/ColorRect8/Match8.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 13, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 13, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 13, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 13, 3))
		$First10/ColorRect9/Match9.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 12, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 12, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 12, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 12, 3))
		$First10/ColorRect10/Match10.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 11, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 11, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 11, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 11, 3))
		$Last10/ColorRect/Match1.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 10, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 10, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 10, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 10, 3))
		$Last10/ColorRect2/Match2.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 9, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 9, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 9, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 9, 3))
		$Last10/ColorRect3/Match3.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 8, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 8, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 8, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 8, 3))
		$Last10/ColorRect4/Match4.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 7, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 7, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 7, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 7, 3))
		$Last10/ColorRect5/Match5.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 6, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 6, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 6, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 6, 3))
		$Last10/ColorRect6/Match6.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 5, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 5, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 5, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 5, 3))
		$Last10/ColorRect7/Match7.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 4, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 4, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 4, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 4, 3))
		$Last10/ColorRect8/Match8.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 3, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 3, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 3, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 3, 3))
		$Last10/ColorRect9/Match9.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 2, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 2, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 2, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 2, 3))
		$Last10/ColorRect10/Match10.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 1, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 1, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 1, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 1, 3))

	if Global.SeasonWeek >= 6 and leaguescheduleweek == 5:
		$First10/ColorRect/Match1.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 20, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 20, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 20, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 20, 3))
		$First10/ColorRect2/Match2.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 19, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 19, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 19, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 19, 3))
		$First10/ColorRect3/Match3.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 18, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 18, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 18, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 18, 3))
		$First10/ColorRect4/Match4.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 17, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 17, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 17, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 17, 3))
		$First10/ColorRect5/Match5.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 16, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 16, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 16, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 16, 3))
		$First10/ColorRect6/Match6.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 15, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 15, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 15, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 15, 3))
		$First10/ColorRect7/Match7.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 14, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 14, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 14, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 14, 3))
		$First10/ColorRect8/Match8.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 13, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 13, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 13, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 13, 3))
		$First10/ColorRect9/Match9.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 12, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 12, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 12, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 12, 3))
		$First10/ColorRect10/Match10.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 11, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 11, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 11, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 11, 3))
		$Last10/ColorRect/Match1.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 10, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 10, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 10, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 10, 3))
		$Last10/ColorRect2/Match2.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 9, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 9, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 9, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 9, 3))
		$Last10/ColorRect3/Match3.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 8, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 8, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 8, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 8, 3))
		$Last10/ColorRect4/Match4.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 7, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 7, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 7, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 7, 3))
		$Last10/ColorRect5/Match5.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 6, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 6, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 6, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 6, 3))
		$Last10/ColorRect6/Match6.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 5, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 5, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 5, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 5, 3))
		$Last10/ColorRect7/Match7.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 4, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 4, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 4, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 4, 3))
		$Last10/ColorRect8/Match8.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 3, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 3, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 3, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 3, 3))
		$Last10/ColorRect9/Match9.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 2, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 2, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 2, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 2, 3))
		$Last10/ColorRect10/Match10.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 1, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 1, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 1, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 1, 3))

	if Global.SeasonWeek >= 7 and leaguescheduleweek == 6:
		$First10/ColorRect/Match1.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 20, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 20, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 20, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 20, 3))
		$First10/ColorRect2/Match2.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 19, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 19, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 19, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 19, 3))
		$First10/ColorRect3/Match3.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 18, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 18, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 18, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 18, 3))
		$First10/ColorRect4/Match4.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 17, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 17, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 17, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 17, 3))
		$First10/ColorRect5/Match5.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 16, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 16, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 16, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 16, 3))
		$First10/ColorRect6/Match6.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 15, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 15, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 15, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 15, 3))
		$First10/ColorRect7/Match7.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 14, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 14, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 14, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 14, 3))
		$First10/ColorRect8/Match8.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 13, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 13, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 13, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 13, 3))
		$First10/ColorRect9/Match9.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 12, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 12, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 12, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 12, 3))
		$First10/ColorRect10/Match10.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 11, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 11, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 11, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 11, 3))
		$Last10/ColorRect/Match1.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 10, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 10, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 10, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 10, 3))
		$Last10/ColorRect2/Match2.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 9, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 9, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 9, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 9, 3))
		$Last10/ColorRect3/Match3.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 8, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 8, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 8, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 8, 3))
		$Last10/ColorRect4/Match4.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 7, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 7, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 7, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 7, 3))
		$Last10/ColorRect5/Match5.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 6, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 6, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 6, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 6, 3))
		$Last10/ColorRect6/Match6.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 5, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 5, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 5, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 5, 3))
		$Last10/ColorRect7/Match7.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 4, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 4, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 4, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 4, 3))
		$Last10/ColorRect8/Match8.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 3, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 3, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 3, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 3, 3))
		$Last10/ColorRect9/Match9.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 2, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 2, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 2, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 2, 3))
		$Last10/ColorRect10/Match10.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 1, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 1, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 1, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 1, 3))

	if Global.SeasonWeek >= 8 and leaguescheduleweek == 7:
		$First10/ColorRect/Match1.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 20, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 20, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 20, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 20, 3))
		$First10/ColorRect2/Match2.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 19, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 19, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 19, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 19, 3))
		$First10/ColorRect3/Match3.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 18, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 18, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 18, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 18, 3))
		$First10/ColorRect4/Match4.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 17, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 17, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 17, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 17, 3))
		$First10/ColorRect5/Match5.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 16, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 16, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 16, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 16, 3))
		$First10/ColorRect6/Match6.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 15, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 15, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 15, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 15, 3))
		$First10/ColorRect7/Match7.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 14, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 14, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 14, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 14, 3))
		$First10/ColorRect8/Match8.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 13, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 13, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 13, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 13, 3))
		$First10/ColorRect9/Match9.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 12, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 12, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 12, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 12, 3))
		$First10/ColorRect10/Match10.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 11, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 11, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 11, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 11, 3))
		$Last10/ColorRect/Match1.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 10, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 10, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 10, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 10, 3))
		$Last10/ColorRect2/Match2.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 9, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 9, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 9, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 9, 3))
		$Last10/ColorRect3/Match3.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 8, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 8, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 8, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 8, 3))
		$Last10/ColorRect4/Match4.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 7, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 7, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 7, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 7, 3))
		$Last10/ColorRect5/Match5.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 6, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 6, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 6, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 6, 3))
		$Last10/ColorRect6/Match6.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 5, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 5, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 5, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 5, 3))
		$Last10/ColorRect7/Match7.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 4, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 4, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 4, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 4, 3))
		$Last10/ColorRect8/Match8.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 3, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 3, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 3, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 3, 3))
		$Last10/ColorRect9/Match9.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 2, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 2, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 2, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 2, 3))
		$Last10/ColorRect10/Match10.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 1, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 1, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 1, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 1, 3))

	if Global.SeasonWeek >= 9 and leaguescheduleweek == 8:
		$First10/ColorRect/Match1.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 20, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 20, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 20, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 20, 3))
		$First10/ColorRect2/Match2.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 19, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 19, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 19, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 19, 3))
		$First10/ColorRect3/Match3.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 18, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 18, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 18, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 18, 3))
		$First10/ColorRect4/Match4.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 17, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 17, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 17, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 17, 3))
		$First10/ColorRect5/Match5.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 16, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 16, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 16, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 16, 3))
		$First10/ColorRect6/Match6.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 15, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 15, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 15, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 15, 3))
		$First10/ColorRect7/Match7.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 14, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 14, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 14, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 14, 3))
		$First10/ColorRect8/Match8.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 13, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 13, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 13, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 13, 3))
		$First10/ColorRect9/Match9.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 12, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 12, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 12, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 12, 3))
		$First10/ColorRect10/Match10.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 11, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 11, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 11, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 11, 3))
		$Last10/ColorRect/Match1.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 10, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 10, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 10, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 10, 3))
		$Last10/ColorRect2/Match2.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 9, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 9, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 9, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 9, 3))
		$Last10/ColorRect3/Match3.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 8, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 8, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 8, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 8, 3))
		$Last10/ColorRect4/Match4.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 7, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 7, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 7, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 7, 3))
		$Last10/ColorRect5/Match5.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 6, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 6, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 6, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 6, 3))
		$Last10/ColorRect6/Match6.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 5, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 5, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 5, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 5, 3))
		$Last10/ColorRect7/Match7.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 4, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 4, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 4, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 4, 3))
		$Last10/ColorRect8/Match8.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 3, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 3, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 3, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 3, 3))
		$Last10/ColorRect9/Match9.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 2, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 2, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 2, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 2, 3))
		$Last10/ColorRect10/Match10.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 1, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 1, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 1, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 1, 3))

	if Global.SeasonWeek >= 10 and leaguescheduleweek == 9:
		$First10/ColorRect/Match1.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 20, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 20, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 20, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 20, 3))
		$First10/ColorRect2/Match2.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 19, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 19, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 19, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 19, 3))
		$First10/ColorRect3/Match3.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 18, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 18, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 18, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 18, 3))
		$First10/ColorRect4/Match4.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 17, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 17, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 17, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 17, 3))
		$First10/ColorRect5/Match5.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 16, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 16, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 16, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 16, 3))
		$First10/ColorRect6/Match6.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 15, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 15, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 15, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 15, 3))
		$First10/ColorRect7/Match7.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 14, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 14, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 14, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 14, 3))
		$First10/ColorRect8/Match8.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 13, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 13, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 13, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 13, 3))
		$First10/ColorRect9/Match9.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 12, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 12, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 12, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 12, 3))
		$First10/ColorRect10/Match10.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 11, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 11, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 11, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 11, 3))
		$Last10/ColorRect/Match1.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 10, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 10, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 10, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 10, 3))
		$Last10/ColorRect2/Match2.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 9, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 9, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 9, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 9, 3))
		$Last10/ColorRect3/Match3.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 8, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 8, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 8, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 8, 3))
		$Last10/ColorRect4/Match4.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 7, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 7, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 7, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 7, 3))
		$Last10/ColorRect5/Match5.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 6, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 6, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 6, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 6, 3))
		$Last10/ColorRect6/Match6.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 5, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 5, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 5, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 5, 3))
		$Last10/ColorRect7/Match7.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 4, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 4, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 4, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 4, 3))
		$Last10/ColorRect8/Match8.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 3, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 3, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 3, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 3, 3))
		$Last10/ColorRect9/Match9.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 2, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 2, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 2, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 2, 3))
		$Last10/ColorRect10/Match10.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 1, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 1, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 1, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 1, 3))

	if Global.SeasonWeek >= 11 and leaguescheduleweek == 10:
		$First10/ColorRect/Match1.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 20, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 20, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 20, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 20, 3))
		$First10/ColorRect2/Match2.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 19, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 19, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 19, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 19, 3))
		$First10/ColorRect3/Match3.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 18, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 18, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 18, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 18, 3))
		$First10/ColorRect4/Match4.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 17, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 17, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 17, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 17, 3))
		$First10/ColorRect5/Match5.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 16, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 16, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 16, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 16, 3))
		$First10/ColorRect6/Match6.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 15, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 15, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 15, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 15, 3))
		$First10/ColorRect7/Match7.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 14, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 14, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 14, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 14, 3))
		$First10/ColorRect8/Match8.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 13, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 13, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 13, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 13, 3))
		$First10/ColorRect9/Match9.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 12, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 12, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 12, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 12, 3))
		$First10/ColorRect10/Match10.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 11, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 11, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 11, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 11, 3))
		$Last10/ColorRect/Match1.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 10, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 10, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 10, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 10, 3))
		$Last10/ColorRect2/Match2.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 9, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 9, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 9, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 9, 3))
		$Last10/ColorRect3/Match3.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 8, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 8, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 8, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 8, 3))
		$Last10/ColorRect4/Match4.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 7, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 7, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 7, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 7, 3))
		$Last10/ColorRect5/Match5.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 6, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 6, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 6, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 6, 3))
		$Last10/ColorRect6/Match6.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 5, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 5, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 5, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 5, 3))
		$Last10/ColorRect7/Match7.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 4, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 4, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 4, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 4, 3))
		$Last10/ColorRect8/Match8.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 3, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 3, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 3, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 3, 3))
		$Last10/ColorRect9/Match9.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 2, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 2, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 2, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 2, 3))
		$Last10/ColorRect10/Match10.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 1, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 1, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 1, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 1, 3))

	if Global.SeasonWeek >= 12 and leaguescheduleweek == 11:
		$First10/ColorRect/Match1.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 20, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 20, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 20, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 20, 3))
		$First10/ColorRect2/Match2.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 19, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 19, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 19, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 19, 3))
		$First10/ColorRect3/Match3.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 18, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 18, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 18, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 18, 3))
		$First10/ColorRect4/Match4.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 17, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 17, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 17, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 17, 3))
		$First10/ColorRect5/Match5.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 16, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 16, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 16, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 16, 3))
		$First10/ColorRect6/Match6.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 15, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 15, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 15, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 15, 3))
		$First10/ColorRect7/Match7.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 14, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 14, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 14, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 14, 3))
		$First10/ColorRect8/Match8.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 13, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 13, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 13, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 13, 3))
		$First10/ColorRect9/Match9.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 12, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 12, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 12, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 12, 3))
		$First10/ColorRect10/Match10.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 11, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 11, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 11, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 11, 3))
		$Last10/ColorRect/Match1.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 10, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 10, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 10, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 10, 3))
		$Last10/ColorRect2/Match2.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 9, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 9, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 9, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 9, 3))
		$Last10/ColorRect3/Match3.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 8, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 8, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 8, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 8, 3))
		$Last10/ColorRect4/Match4.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 7, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 7, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 7, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 7, 3))
		$Last10/ColorRect5/Match5.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 6, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 6, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 6, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 6, 3))
		$Last10/ColorRect6/Match6.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 5, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 5, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 5, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 5, 3))
		$Last10/ColorRect7/Match7.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 4, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 4, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 4, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 4, 3))
		$Last10/ColorRect8/Match8.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 3, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 3, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 3, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 3, 3))
		$Last10/ColorRect9/Match9.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 2, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 2, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 2, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 2, 3))
		$Last10/ColorRect10/Match10.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 1, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 1, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 1, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 1, 3))

	if Global.SeasonWeek >= 13 and leaguescheduleweek == 12:
		$First10/ColorRect/Match1.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 20, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 20, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 20, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 20, 3))
		$First10/ColorRect2/Match2.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 19, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 19, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 19, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 19, 3))
		$First10/ColorRect3/Match3.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 18, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 18, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 18, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 18, 3))
		$First10/ColorRect4/Match4.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 17, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 17, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 17, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 17, 3))
		$First10/ColorRect5/Match5.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 16, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 16, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 16, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 16, 3))
		$First10/ColorRect6/Match6.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 15, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 15, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 15, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 15, 3))
		$First10/ColorRect7/Match7.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 14, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 14, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 14, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 14, 3))
		$First10/ColorRect8/Match8.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 13, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 13, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 13, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 13, 3))
		$First10/ColorRect9/Match9.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 12, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 12, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 12, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 12, 3))
		$First10/ColorRect10/Match10.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 11, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 11, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 11, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 11, 3))
		$Last10/ColorRect/Match1.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 10, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 10, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 10, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 10, 3))
		$Last10/ColorRect2/Match2.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 9, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 9, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 9, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 9, 3))
		$Last10/ColorRect3/Match3.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 8, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 8, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 8, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 8, 3))
		$Last10/ColorRect4/Match4.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 7, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 7, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 7, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 7, 3))
		$Last10/ColorRect5/Match5.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 6, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 6, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 6, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 6, 3))
		$Last10/ColorRect6/Match6.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 5, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 5, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 5, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 5, 3))
		$Last10/ColorRect7/Match7.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 4, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 4, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 4, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 4, 3))
		$Last10/ColorRect8/Match8.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 3, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 3, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 3, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 3, 3))
		$Last10/ColorRect9/Match9.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 2, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 2, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 2, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 2, 3))
		$Last10/ColorRect10/Match10.text = "Week " + str(leaguescheduleweek) + ": " + str(Results.get_match_total((leaguescheduleweek * 20) - 1, 0)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 1, 2)) + " - " + str(Results.get_match_total((leaguescheduleweek * 20) - 1, 1)) + " " + str(Results.get_match_total((leaguescheduleweek * 20) - 1, 3))

	if Global.SeasonWeek >= 14 and leaguescheduleweek == 13:
		$First10/ColorRect/Match1.text = "Alpha CQF: " + str(Results.get_match_total(240, 0)) + " " + str(Results.get_match_total(240, 2)) + " - " + str(Results.get_match_total(240, 1)) + " " + str(Results.get_match_total(240, 3))
		$First10/ColorRect2/Match2.text = "Alpha CQF: " + str(Results.get_match_total(241, 0)) + " " + str(Results.get_match_total(241, 2)) + " - " + str(Results.get_match_total(241, 1)) + " " + str(Results.get_match_total(241, 3))
		$First10/ColorRect3/Match3.text = "Alpha CQF: " + str(Results.get_match_total(242, 0)) + " " + str(Results.get_match_total(242, 2)) + " - " + str(Results.get_match_total(242, 1)) + " " + str(Results.get_match_total(242, 3))
		$First10/ColorRect4/Match4.text = "Alpha CQF: " + str(Results.get_match_total(243, 0)) + " " + str(Results.get_match_total(243, 2)) + " - " + str(Results.get_match_total(243, 1)) + " " + str(Results.get_match_total(243, 3))
		$First10/ColorRect5/Match5.text = "Omega CQF: " + str(Results.get_match_total(244, 0)) + " " + str(Results.get_match_total(244, 2)) + " - " + str(Results.get_match_total(244, 1)) + " " + str(Results.get_match_total(244, 3))
		$First10/ColorRect6/Match6.text = "Omega CQF: " + str(Results.get_match_total(245, 0)) + " " + str(Results.get_match_total(245, 2)) + " - " + str(Results.get_match_total(245, 1)) + " " + str(Results.get_match_total(245, 3))
		$First10/ColorRect7/Match7.text = "Omega CQF: " + str(Results.get_match_total(246, 0)) + " " + str(Results.get_match_total(246, 2)) + " - " + str(Results.get_match_total(246, 1)) + " " + str(Results.get_match_total(246, 3))
		$First10/ColorRect8/Match8.text = "Omega CQF: " + str(Results.get_match_total(247, 0)) + " " + str(Results.get_match_total(247, 2)) + " - " + str(Results.get_match_total(247, 1)) + " " + str(Results.get_match_total(247, 3))
	
	
	if Global.SeasonWeek >= 15 and leaguescheduleweek == 13:
		$First10/ColorRect9/Match9.text = "Alpha CSF: " + str(Results.get_match_total(248, 0)) + " " + str(Results.get_match_total(248, 2)) + " - " + str(Results.get_match_total(248, 1)) + " " + str(Results.get_match_total(248, 3))
		$First10/ColorRect10/Match10.text = "Alpha CSF: " + str(Results.get_match_total(249, 0)) + " " + str(Results.get_match_total(249, 2)) + " - " + str(Results.get_match_total(249, 1)) + " " + str(Results.get_match_total(249, 3))
		$Last10/ColorRect/Match1.text = "Omega CSF: " + str(Results.get_match_total(250, 0)) + " " + str(Results.get_match_total(250, 2)) + " - " + str(Results.get_match_total(250, 1)) + " " + str(Results.get_match_total(250, 3))
		$Last10/ColorRect2/Match2.text = "Omega CSF: " + str(Results.get_match_total(251, 0)) + " " + str(Results.get_match_total(251, 2)) + " - " + str(Results.get_match_total(251, 1)) + " " + str(Results.get_match_total(251, 3))
	
	if Global.SeasonWeek >= 16 and leaguescheduleweek == 13:
		$Last10/ColorRect3/Match3.text = "Alpha CF: " + str(Results.get_match_total(252, 0)) + " " + str(Results.get_match_total(252, 2)) + " - " + str(Results.get_match_total(252, 1)) + " " + str(Results.get_match_total(252, 3))
		$Last10/ColorRect4/Match4.text = "Omega CF: " + str(Results.get_match_total(253, 0)) + " " + str(Results.get_match_total(253, 2)) + " - " + str(Results.get_match_total(253, 1)) + " " + str(Results.get_match_total(253, 3))
	
	if Global.SeasonWeek >= 17 and leaguescheduleweek == 13:
		$Last10/ColorRect5/Match5.text = "UDL Championship: " + str(Results.get_match_total(254, 0)) + " " + str(Results.get_match_total(254, 2)) + " - " + str(Results.get_match_total(254, 1)) + " " + str(Results.get_match_total(254, 3))

func _on_button_2_button_up() -> void:
	get_tree().change_scene_to_file("res://scenes/seasonhub.tscn")


func _on_week_1_button_up() -> void:
	leaguescheduleweek = 1
	schedule_view()


func _on_week_2_button_up() -> void:
	leaguescheduleweek = 2
	schedule_view()


func _on_week_3_button_up() -> void:
	leaguescheduleweek = 3
	schedule_view()


func _on_week_4_button_up() -> void:
	leaguescheduleweek = 4
	schedule_view()


func _on_week_5_button_up() -> void:
	leaguescheduleweek = 5
	schedule_view()


func _on_week_6_button_up() -> void:
	leaguescheduleweek = 6
	schedule_view()


func _on_week_7_button_up() -> void:
	leaguescheduleweek = 7
	schedule_view()


func _on_week_8_button_up() -> void:
	leaguescheduleweek = 8
	schedule_view()


func _on_week_9_button_up() -> void:
	leaguescheduleweek = 9
	schedule_view()


func _on_week_10_button_up() -> void:
	leaguescheduleweek = 10
	schedule_view()


func _on_week_11_button_up() -> void:
	leaguescheduleweek = 11
	schedule_view()


func _on_week_12_button_up() -> void:
	leaguescheduleweek = 12
	schedule_view()


func _on_week_13_button_up() -> void:
	leaguescheduleweek = 13
	schedule_view()
